server:
  port: 8082

spring:
  application:
    name: restaurantmanager

  kafka:
    bootstrap-servers: http://localhost:9092
    consumer:
      group-id: restaurant-group
    producer:
      bootstrap-servers: http://localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: docker

  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
