services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    tty: true
    ports:
      - 5432:5432
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=restaurant
    networks:
      - teste_PGE_network

  db2:
    container_name: db2
    image: postgres:15
    restart: always
    tty: true
    ports:
      - 5433:5432
    volumes:
      - .docker/dbdata2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=order
    networks:
      - teste_PGE_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    ports:
      - 22181:2181

  kafka-host:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # gateway:
  #   container_name: gateway
  #   build: ./gateway
  #   restart: unless-stopped
  #   ports:
  #     - 9090:9090
  #   networks:
  #     - teste_PGE_network

networks:
  teste_PGE_network:
