server:
  port: 9090

spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]": # Aplica a todas as rotas
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: order-swagger
          uri: http://localhost:8081
          predicates:
            - Path=/order/doc
          filters:
            - RewritePath=/order/doc, /swagger-ui/index.html

        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/order/**

        - id: restaurant-manager-swagger
          uri: http://localhost:8082
          predicates:
            - Path=/restaurant-manager/doc
          filters:
            - RewritePath=/restaurant-manager/doc, /swagger-ui/index.html

        - id: restaurant-manager
          uri: http://localhost:8082
          predicates:
            - Path=/restaurant-manager/**
